baseurl = "https://amor.cms.hu-berlin.de/~jaehnicp/"
title = "WBI/ML group, HU Berlin"
copyright = "&copy; 2018 Patrick Jähnichen"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
disqusShortname = "patrickjhnichen"

# Enable analytics by entering your Google Analytics tracking ID
# googleAnalytics = "UA-80913130-1"


[params]
    name = "Patrick Jähnichen"
    role = "Postdoctoral Researcher in Machine Learning"
    organization = "Humboldt-Universität zu Berlin"
    interests = ["Topic modeling", "Dynamic Bayesian Models", "Gaussian processes", "Scalable Baysian Inference"]
    email = "firstname.lastname@hu-berlin.de (replace \"ä\" by \"ae\")"
    office_hours = "Office hours: Thursdays, 1 pm - 3 pm"
    address = "Knowledge Management in Bioinformatics, Humboldt-Universität zu Berlin (Visitors: Rudower Chaussee 25, Bldg. IV, Room 407 (fourth floor), 12489 Berlin; Postal: Unter den Linden 6, 10099 Berlin)"
    phone = "+49 (0)30 2093 3167"

    # Date format (refer to Go's formatting options)
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "Mon, Jan 2, 2006"

    # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
    math = true

    # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
    custom_css = []
    custom_js  = []

    #set current term
    current_term = "Summer 2018"

    [[params.education]]
        course = "PhD in NLP/ML"
        institution = "Leipzig University"
        year = 2016

    [[params.education]]
        course = "MSc in NLP/ML"
        institution = "Leipzig University"
        year = 2010

    [[params.education]]
        course = "BSc in Applied Computer Science"
        institution = "Stuttgart University of Cooperative Education (BA)"
        year = 2005

    # Activities (PCs, reviewing, etc.)

    [[params.activities]]
        institution = "ICLR conference"
        year = "2018"
        activity = "Reviewer, Member of Program Committee"
    [[params.activities]]
        institution = "ICML conference"
        year = "2018"
        activity = "Reviewer, Member of Program Committee"
    [[params.activities]]
        institution = "NIPS conference"
        year = "2016, 2017"
        activity = "Reviewer, Member of Program Committee"
    [[params.activities]]
        institution = "BMC Bioinformatics"
        year = "since 2018"
        activity = "Reviewer"
    [[params.activities]]
        institution = "Journal of Machine Learning Research (JMLR)"
        year = "since 2017"
        activity = "Reviewer"
    [[params.activities]]
        institution = "Open Civil Engineering Journal"
        year = "since 2016"
        activity = "Reviewer"
    [[params.activities]]
        institution = "Genomics and Computational Biology"
        year = "since 2016"
        activity = "Reviewer"
    [[params.activities]]
        institution = "Digital Humanities Quarterly"
        year = "since 2016"
        activity = "Reviewer"
    [[params.activities]]
        institution = "Advances in Approximate Bayesian Inference (Workshop at NIPS)"
        year = "since 2015"
        activity = "Reviewer, Member of Program Committee"

    # Social/Academic Networking
    #
    # Icon pack "fa" includes the following social network icons:
    #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
    #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
    #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
    #
    # Icon pack "ai" includes the following academic network icons:
    #   google-scholar, arxiv, orcid, researchgate, mendeley
    #   Full list: https://jpswalsh.github.io/academicons/

#    [[params.social]]
#        icon = "envelope"
#        icon_pack = "fa"
#        link = "<script type=\"text/javascript\">eval(unescape(\"%65%6c%66%6a%72%30%33%3d%5b%27%25%37%30%25%36%31%25%37%34%25%37%32%25%36%39%25%36%33%25%36%62%25%32%65%25%36%61%25%36%31%25%36%35%25%36%38%25%36%65%25%36%39%25%36%33%25%36%38%25%36%35%25%36%65%27%2c%5b%27%25%36%34%25%36%35%27%2c%27%25%36%38%25%37%35%25%32%64%25%36%32%25%36%35%25%37%32%25%36%63%25%36%39%25%36%65%27%5d%2e%72%65%76%65%72%73%65%28%29%2e%6a%6f%69%6e%28%27%2e%27%29%5d%2e%6a%6f%69%6e%28%27%40%27%29%3b%71%75%6a%67%64%39%36%3d%27%62%6c%61%27%3b%64%6f%63%75%6d%65%6e%74%2e%77%72%69%74%65%28%71%75%6a%67%64%39%36%2e%6c%69%6e%6b%28%27%6d%61%69%27%2b%27%6c%74%6f%3a%27%2b%65%6c%66%6a%72%30%33%29%29%3b\"));</script>"

   [[params.social]]
       icon = "google-scholar"
       icon_pack = "ai"
       link = "https://scholar.google.de/citations?user=p4f9rBIAAAAJ"

    [[params.social]]
        icon = "researchgate"
        icon_pack = "ai"
        link = "https://www.researchgate.net/profile/Patrick_Jaehnichen"

    [[params.social]]
        icon = "github"
        icon_pack = "fa"
        link = "//github.com/patrickjae"

    [[params.social]]
        icon = "bitbucket"
        icon_pack = "fa"
        link = "https://bitbucket.org/hotblack_desiato/"

# Navigation Links
#
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
    name = "Home"
    url = "#top"
    weight = 1

[[menu.main]]
    name = "Publications"
    url = "#publications"
    weight = 2

# [[menu.main]]
#     name = "Posts"
#     url = "#posts"
#     weight = 3

[[menu.main]]
    name = "Projects and Materials"
    url = "#projects"
    weight = 4

[[menu.main]]
    name = "Teaching"
    url = "#teaching"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 6
